apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: frlxbyaao-python
  janus-idp.io/tekton: frlxbyaao-python
  backstage.io/kubernetes-id: frlxbyaao-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: frlxbyaao-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
